version: "3.9"

services:
  db:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: bunnings_ssa
      MYSQL_USER: bunnings_user
      MYSQL_PASSWORD: bunnings_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./backend/.env
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm ci && npm start"
    env_file:
      - ./frontend/.env
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mysql_data:
