export const s = {
  page: { padding: '1.5rem 2rem', maxWidth: 960, margin: '0 auto' },
  h1: { fontSize: 22, fontWeight: 600, marginBottom: '1.25rem', color: '#1a1a18' },
  h3: { fontSize: 15, fontWeight: 600, marginBottom: '.75rem', color: '#1a1a18' },
  formCard: { background: '#fff', border: '1px solid #e5e5e2', borderRadius: 10, padding: '1.25rem 1.5rem', marginBottom: '1.5rem' },
  resultCard: { background: '#fff', border: '1px solid #e5e5e2', borderRadius: 10, padding: '1rem 1.25rem', marginBottom: '.75rem' },
  grid2: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10 },
  fieldLabel: { fontSize: 12, color: '#666', display: 'block', marginBottom: 4 },
  input: { width: '100%', padding: '7px 10px', fontSize: 13, border: '1px solid #ddd', borderRadius: 6, boxSizing: 'border-box', outline: 'none' },
  btnPrimary: { padding: '8px 18px', fontSize: 13, fontWeight: 600, background: '#d32f2f', color: '#fff', border: 'none', borderRadius: 8, cursor: 'pointer' },
  btnGhost: { padding: '8px 18px', fontSize: 13, background: 'transparent', color: '#555', border: '1px solid #ddd', borderRadius: 8, cursor: 'pointer' },
  btnSm: { fontSize: 12, padding: '4px 10px', background: 'transparent', border: '1px solid #ddd', borderRadius: 6, cursor: 'pointer', marginRight: 4 },
  table: { width: '100%', borderCollapse: 'collapse', fontSize: 13 },
  th: { textAlign: 'left', padding: '8px 12px', background: '#f5f5f3', color: '#555', fontSize: 12, fontWeight: 500, borderBottom: '1px solid #e5e5e2' },
  tr: { borderBottom: '1px solid #f0f0ee' },
  td: { padding: '9px 12px', color: '#333' },
  error: { color: '#c0392b', fontSize: 13 },
  muted: { color: '#888', fontSize: 13 },
  resultRow: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '5px 0', borderTop: '1px solid #f0f0ee', fontSize: 13 },
};
