[program:bunnings-ssa]
directory=/srv/bunnings-ssa/backend
command=/srv/bunnings-ssa/.venv/bin/gunicorn backend.wsgi:application --bind 127.0.0.1:8000 --workers 3
environment=DJANGO_SETTINGS_MODULE="backend.settings.production"
autostart=true
autorestart=true
stdout_logfile=/var/log/bunnings-ssa.out.log
stderr_logfile=/var/log/bunnings-ssa.err.log
user=www-data
