# Generated by Django 4.2.13 on 2026-05-02 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='members_needed',
        ),
    ]
