# Generated by Django 4.2.13 on 2026-05-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssa', '0006_delete_useremailsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
